package com.gimnasio.persistences;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Descuentos generated by hbm2java
 */
public class Descuentos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal porcentaje;
     private Set clientePaquetes = new HashSet(0);

    public Descuentos() {
    }

	
    public Descuentos(String nombre, BigDecimal porcentaje) {
        this.nombre = nombre;
        this.porcentaje = porcentaje;
    }
    public Descuentos(String nombre, BigDecimal porcentaje, Set clientePaquetes) {
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.clientePaquetes = clientePaquetes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set getClientePaquetes() {
        return this.clientePaquetes;
    }
    
    public void setClientePaquetes(Set clientePaquetes) {
        this.clientePaquetes = clientePaquetes;
    }




}


