package com.gimnasio.persistences;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Paquetes generated by hbm2java
 */
public class Paquetes  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal precioBase;
     private short ynTiquetera;
     private Set clientePaquetes = new HashSet(0);

    public Paquetes() {
    }

	
    public Paquetes(String nombre, BigDecimal precioBase, short ynTiquetera) {
        this.nombre = nombre;
        this.precioBase = precioBase;
        this.ynTiquetera = ynTiquetera;
    }
    public Paquetes(String nombre, BigDecimal precioBase, short ynTiquetera, Set clientePaquetes) {
       this.nombre = nombre;
       this.precioBase = precioBase;
       this.ynTiquetera = ynTiquetera;
       this.clientePaquetes = clientePaquetes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecioBase() {
        return this.precioBase;
    }
    
    public void setPrecioBase(BigDecimal precioBase) {
        this.precioBase = precioBase;
    }
    public short getYnTiquetera() {
        return this.ynTiquetera;
    }
    
    public void setYnTiquetera(short ynTiquetera) {
        this.ynTiquetera = ynTiquetera;
    }
    public Set getClientePaquetes() {
        return this.clientePaquetes;
    }
    
    public void setClientePaquetes(Set clientePaquetes) {
        this.clientePaquetes = clientePaquetes;
    }




}


