package com.gimnasio.model;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ClientePaqueteDto generated by hbm2java
 */
public class ClientePaqueteDto implements java.io.Serializable {

    private Long id;
    private ClienteDto clienteDto;
    private DescuentoDto descuentoDto;
    private PaqueteDto paquetes;
    private UsuarioDto usuarioDto;
    private BigDecimal valorTotal;
    private short ynActivo;
    private Date fechaIniciaPaquete;
    private Date fechaFinalizaPaquete;
    private Date fechaRegistro;
    private Date fechaModificacion;

    public ClientePaqueteDto() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ClienteDto getClienteDto() {
        return clienteDto;
    }

    public void setClienteDto(ClienteDto clienteDto) {
        this.clienteDto = clienteDto;
    }

    public DescuentoDto getDescuentoDto() {
        return descuentoDto;
    }

    public void setDescuentoDto(DescuentoDto descuentoDto) {
        this.descuentoDto = descuentoDto;
    }

    public PaqueteDto getPaquetes() {
        return paquetes;
    }

    public void setPaquetes(PaqueteDto paquetes) {
        this.paquetes = paquetes;
    }

    public UsuarioDto getUsuarioDto() {
        return usuarioDto;
    }

    public void setUsuarioDto(UsuarioDto usuarioDto) {
        this.usuarioDto = usuarioDto;
    }

    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    public short getYnActivo() {
        return ynActivo;
    }

    public void setYnActivo(short ynActivo) {
        this.ynActivo = ynActivo;
    }

    public Date getFechaIniciaPaquete() {
        return fechaIniciaPaquete;
    }

    public void setFechaIniciaPaquete(Date fechaIniciaPaquete) {
        this.fechaIniciaPaquete = fechaIniciaPaquete;
    }

    public Date getFechaFinalizaPaquete() {
        return fechaFinalizaPaquete;
    }

    public void setFechaFinalizaPaquete(Date fechaFinalizaPaquete) {
        this.fechaFinalizaPaquete = fechaFinalizaPaquete;
    }

    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Date getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

}
