package com.gimnasio.model;
// Generated ago 2, 2016 10:46:44 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClientePaquete generated by hbm2java
 */
public class ClientePaquete  implements java.io.Serializable {


     private Long id;
     private Clientes clientes;
     private Descuentos descuentos;
     private Paquetes paquetes;
     private Usuarios usuarios;
     private BigDecimal valorTotal;
     private short ynActivo;
     private Date fechaIniciaPaquete;
     private Date fechaFinalizaPaquete;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set pagoses = new HashSet(0);

    public ClientePaquete() {
    }

	
    public ClientePaquete(Clientes clientes, Paquetes paquetes, Usuarios usuarios, BigDecimal valorTotal, short ynActivo, Date fechaIniciaPaquete, Date fechaFinalizaPaquete, Date fechaRegistro, Date fechaModificacion) {
        this.clientes = clientes;
        this.paquetes = paquetes;
        this.usuarios = usuarios;
        this.valorTotal = valorTotal;
        this.ynActivo = ynActivo;
        this.fechaIniciaPaquete = fechaIniciaPaquete;
        this.fechaFinalizaPaquete = fechaFinalizaPaquete;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public ClientePaquete(Clientes clientes, Descuentos descuentos, Paquetes paquetes, Usuarios usuarios, BigDecimal valorTotal, short ynActivo, Date fechaIniciaPaquete, Date fechaFinalizaPaquete, Date fechaRegistro, Date fechaModificacion, Set pagoses) {
       this.clientes = clientes;
       this.descuentos = descuentos;
       this.paquetes = paquetes;
       this.usuarios = usuarios;
       this.valorTotal = valorTotal;
       this.ynActivo = ynActivo;
       this.fechaIniciaPaquete = fechaIniciaPaquete;
       this.fechaFinalizaPaquete = fechaFinalizaPaquete;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.pagoses = pagoses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Descuentos getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Descuentos descuentos) {
        this.descuentos = descuentos;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public short getYnActivo() {
        return this.ynActivo;
    }
    
    public void setYnActivo(short ynActivo) {
        this.ynActivo = ynActivo;
    }
    public Date getFechaIniciaPaquete() {
        return this.fechaIniciaPaquete;
    }
    
    public void setFechaIniciaPaquete(Date fechaIniciaPaquete) {
        this.fechaIniciaPaquete = fechaIniciaPaquete;
    }
    public Date getFechaFinalizaPaquete() {
        return this.fechaFinalizaPaquete;
    }
    
    public void setFechaFinalizaPaquete(Date fechaFinalizaPaquete) {
        this.fechaFinalizaPaquete = fechaFinalizaPaquete;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }




}


