package com.gimnasio.model;
// Generated ago 2, 2016 10:46:44 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Ingresos generated by hbm2java
 */
public class Ingresos  implements java.io.Serializable {


     private long id;
     private Usuarios usuarios;
     private String tipoIngreso;
     private BigDecimal valor;
     private Date fechaRegistro;

    public Ingresos() {
    }

    public Ingresos(long id, Usuarios usuarios, String tipoIngreso, BigDecimal valor, Date fechaRegistro) {
       this.id = id;
       this.usuarios = usuarios;
       this.tipoIngreso = tipoIngreso;
       this.valor = valor;
       this.fechaRegistro = fechaRegistro;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTipoIngreso() {
        return this.tipoIngreso;
    }
    
    public void setTipoIngreso(String tipoIngreso) {
        this.tipoIngreso = tipoIngreso;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


