package com.gimnasio.model;
// Generated jul 28, 2016 11:18:13 p.m. by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Long id;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private short tipoDocumento;
     private String numeroDocumento;
     private String lugarExpedicion;
     private short genero;
     private short estadoCivil;
     private Date fechaNacimiento;
     private String direccion;
     private String barrio;
     private String telefono;
     private String movil;
     private String foto;
     private String email;
     private Date createdAt;
     private Date updatedAt;

    public Persona() {
    }

	
    public Persona(String primerNombre, String primerApellido, short tipoDocumento, String numeroDocumento, short genero, short estadoCivil, Date fechaNacimiento, String direccion, String barrio, String movil, String foto, String email, Date createdAt, Date updatedAt) {
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.genero = genero;
        this.estadoCivil = estadoCivil;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.barrio = barrio;
        this.movil = movil;
        this.foto = foto;
        this.email = email;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Persona(String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, short tipoDocumento, String numeroDocumento, String lugarExpedicion, short genero, short estadoCivil, Date fechaNacimiento, String direccion, String barrio, String telefono, String movil, String foto, String email, Date createdAt, Date updatedAt) {
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.lugarExpedicion = lugarExpedicion;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.barrio = barrio;
       this.telefono = telefono;
       this.movil = movil;
       this.foto = foto;
       this.email = email;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public short getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(short tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getLugarExpedicion() {
        return this.lugarExpedicion;
    }
    
    public void setLugarExpedicion(String lugarExpedicion) {
        this.lugarExpedicion = lugarExpedicion;
    }
    public short getGenero() {
        return this.genero;
    }
    
    public void setGenero(short genero) {
        this.genero = genero;
    }
    public short getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(short estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMovil() {
        return this.movil;
    }
    
    public void setMovil(String movil) {
        this.movil = movil;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


