/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gimnasio.views;

import com.gimnasio.controller.Operaciones;
import com.gimnasio.model.UsuarioDto;
import com.gimnasio.util.Util;
import java.awt.Font;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodolfo
 */
public class frmPrincipal extends javax.swing.JFrame {

    private frmClientesIngresos clientesIngresosView;
    private frmRegistrarPagos registrarPagosView;
    private frmBuscarCliente buscarClienteView;
    private frmReporteCumpleanos cumpleanosView;
    private frmReporteFisioterapia reporteFisioterapiaView;
    private frmFisioterapia fisitorepiaView;
    private frmDescuentos descuentoView;
    private frmCafeteria cafeteriaView;
    private frmProductos productoView;
    private frmUsuarios usuarioView;
    private frmPaquetes paqueteView;
    private frmClientes clienteView;
    private frmPagos pagosView;

    private UsuarioDto usuarioSessionDto;
    private Operaciones operacion;

    public frmPrincipal() {
        initComponents();
        // this.setSize(1250, 700);
        Util.setCentrarJFrame(this, null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Util.setFuncionesJFrame(this, false);
        this.registrarPagosView = null;
        this.buscarClienteView = null;
        this.fisitorepiaView = null;
        this.cumpleanosView = null;
        this.reporteFisioterapiaView = null;
        this.descuentoView = null;
        this.productoView = null;
        this.paqueteView = null;
        this.clienteView = null;
        this.pagosView = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdstPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPaquetes = new javax.swing.JMenuItem();
        menuDescuentos = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuCrear_usuario = new javax.swing.JMenuItem();
        menuBuscar_cliente1 = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuCrear_cliente = new javax.swing.JMenuItem();
        menuBuscar_cliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPagos = new javax.swing.JMenuItem();
        menuCafeteria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuReporte_fisioterapia = new javax.swing.JMenuItem();
        menuCumpleanos = new javax.swing.JMenu();
        menuCierre_caja = new javax.swing.JMenuItem();
        menuClientes_activos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdstPrincipalLayout = new javax.swing.GroupLayout(jdstPrincipal);
        jdstPrincipal.setLayout(jdstPrincipalLayout);
        jdstPrincipalLayout.setHorizontalGroup(
            jdstPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jdstPrincipalLayout.setVerticalGroup(
            jdstPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/cog-icon.png"))); // NOI18N
        jMenu1.setText("Administración");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/folder-icon.png"))); // NOI18N
        menuPaquetes.setText("Paquetes");
        menuPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCrearPaquetes(evt);
            }
        });
        jMenu1.add(menuPaquetes);

        menuDescuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/box-in-icon.png"))); // NOI18N
        menuDescuentos.setText("Descuentos");
        menuDescuentos.setToolTipText("");
        menuDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCrearDescuentos(evt);
            }
        });
        jMenu1.add(menuDescuentos);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/apple-2-icon.png"))); // NOI18N
        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCrearPoductos(evt);
            }
        });
        jMenu1.add(menuProductos);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/user-male-alt-icon.png"))); // NOI18N
        menuUsuario.setText("Usuarios");

        menuCrear_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/user-male-alt-icon.png"))); // NOI18N
        menuCrear_usuario.setText("Crear");
        menuCrear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuCrearUsuario(evt);
            }
        });
        menuUsuario.add(menuCrear_usuario);

        menuBuscar_cliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Zoom-icon.png"))); // NOI18N
        menuBuscar_cliente1.setText("Buscar");
        menuBuscar_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuBuscarUsuario(evt);
            }
        });
        menuUsuario.add(menuBuscar_cliente1);

        jMenu1.add(menuUsuario);

        jMenuBar1.add(jMenu1);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/user-male-alt-icon.png"))); // NOI18N
        menuCliente.setText("Clientes");

        menuCrear_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/user-male-alt-icon.png"))); // NOI18N
        menuCrear_cliente.setText("Crear");
        menuCrear_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRegistrarClientes(evt);
            }
        });
        menuCliente.add(menuCrear_cliente);

        menuBuscar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Zoom-icon.png"))); // NOI18N
        menuBuscar_cliente.setText("Buscar");
        menuBuscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBuscarClientes(evt);
            }
        });
        menuCliente.add(menuBuscar_cliente);

        jMenuBar1.add(menuCliente);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/money-icon.png"))); // NOI18N
        jMenu3.setText("Pagos");

        menuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/money-icon.png"))); // NOI18N
        menuPagos.setText("Pagos");
        menuPagos.setToolTipText("");
        menuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRegistrarPagosPlanes(evt);
            }
        });
        jMenu3.add(menuPagos);

        menuCafeteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Juice-icon.png"))); // NOI18N
        menuCafeteria.setText("Cafeteria");
        menuCafeteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRegistrarPagosProductos(evt);
            }
        });
        jMenu3.add(menuCafeteria);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Hand-Touch-2-icon.png"))); // NOI18N
        jMenu4.setText("Registro");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setRegistrarClienteIngresos(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/medical-suitecase-icon.png"))); // NOI18N
        jMenu5.setText("Fisioterapia");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/medical-suitecase-icon.png"))); // NOI18N
        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRegistrarDatosFisioterapeuta(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        menuReporte_fisioterapia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/file-powerpoint-icon.png"))); // NOI18N
        menuReporte_fisioterapia.setText("Reporte");
        menuReporte_fisioterapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporte_fisioterapiaActionPerformed(evt);
            }
        });
        jMenu5.add(menuReporte_fisioterapia);

        jMenuBar1.add(jMenu5);

        menuCumpleanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/file-powerpoint-icon.png"))); // NOI18N
        menuCumpleanos.setText("Reportes");

        menuCierre_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/cash-register-icon.png"))); // NOI18N
        menuCierre_caja.setText("Cierre de Caja");
        menuCierre_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuCierreCaja(evt);
            }
        });
        menuCumpleanos.add(menuCierre_caja);

        menuClientes_activos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/User-green-icon.png"))); // NOI18N
        menuClientes_activos.setText("Clientes Activos");
        menuClientes_activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuClientesActivos(evt);
            }
        });
        menuCumpleanos.add(menuClientes_activos);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Present-icon.png"))); // NOI18N
        jMenuItem3.setText("Cumpleaños");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuCumpleanos(evt);
            }
        });
        menuCumpleanos.add(jMenuItem3);

        jMenuBar1.add(menuCumpleanos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdstPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdstPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setCrearPaquetes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCrearPaquetes
        if (this.paqueteView == null) {
            try {
                this.paqueteView = new frmPaquetes(this, this.operacion);
                frmPrincipal.jdstPrincipal.add(this.paqueteView);
                this.paqueteView.setTitle("Formulario para el registro de paquetes");
                this.paqueteView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
                this.paqueteView.setClosable(true);
                this.paqueteView.setResizable(true);
                this.paqueteView.setVisible(true);
            } catch (Exception ex) {
                JLabel label = new JLabel("Error no controlado, intente nuevamente");
                label.setFont(new Font("consolas", Font.PLAIN, 14));
                JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JLabel label = new JLabel("<html>El formulario para el registro de <b>paquetes</b> ya se encuentra abierto</html>");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_setCrearPaquetes

    /**
     *
     * @param evt
     */
    private void setCrearPoductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCrearPoductos
        try {
            this.productoView = new frmProductos(this, this.operacion);
            frmPrincipal.jdstPrincipal.add(this.productoView);
            this.productoView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
            this.productoView.setResizable(true);
            this.productoView.setClosable(true);
            this.productoView.setVisible(true);
        } catch (Exception ex) {
            JLabel label = new JLabel("Error no controlado, intente nuevamente");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setCrearPoductos

    /**
     *
     * @param evt
     */
    private void setCrearDescuentos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCrearDescuentos
        try {
            this.descuentoView = new frmDescuentos(this, this.operacion);
            frmPrincipal.jdstPrincipal.add(this.descuentoView);
            this.descuentoView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
            this.descuentoView.setResizable(true);
            this.descuentoView.setClosable(true);
            this.descuentoView.setVisible(true);
        } catch (SQLException ex) {
            JLabel label = new JLabel("Error no controlado, intente nuevamente");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setCrearDescuentos

    /**
     *
     * @param evt
     */
    private void setRegistrarPagosPlanes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRegistrarPagosPlanes
        this.buscarClienteView = new frmBuscarCliente(this, this.operacion, "3");
        frmPrincipal.jdstPrincipal.add(this.buscarClienteView);
        this.buscarClienteView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.buscarClienteView.setUsuarioSessionDto(usuarioSessionDto);
        this.buscarClienteView.setResizable(true);
        this.buscarClienteView.setClosable(true);
        this.buscarClienteView.setVisible(true);
    }//GEN-LAST:event_setRegistrarPagosPlanes

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     *
     * @param evt
     */
    private void setBuscarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBuscarClientes
        this.buscarClienteView = new frmBuscarCliente(this, operacion, "1");
        frmPrincipal.jdstPrincipal.add(this.buscarClienteView);
        this.buscarClienteView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.buscarClienteView.setUsuarioSessionDto(usuarioSessionDto);
        this.buscarClienteView.setResizable(true);
        this.buscarClienteView.setClosable(true);
        this.buscarClienteView.setVisible(true);
    }//GEN-LAST:event_setBuscarClientes

    /**
     *
     * @param evt
     */
    private void setRegistrarPagosProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRegistrarPagosProductos
        try {
            this.cafeteriaView = new frmCafeteria(this.operacion);
            this.cafeteriaView.setUsuarioDto(this.usuarioSessionDto);
            frmPrincipal.jdstPrincipal.add(this.cafeteriaView);
            this.cafeteriaView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
            this.cafeteriaView.setResizable(true);
            this.cafeteriaView.setClosable(true);
            this.cafeteriaView.setVisible(true);
        } catch (Exception ex) {
            JLabel label = new JLabel("Error no controlado, intente nuevamente");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setRegistrarPagosProductos
    /**
     *
     * @param evt
     */
    private void setRegistrarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRegistrarClientes
        try {
            this.clienteView = new frmClientes(this, this.operacion);
            this.clienteView.setTitle("Formulario para el registro de clientes");
            this.clienteView.setSize(this.getWidth(), this.getHeight() - 1);
            this.clienteView.setUsuarioSessionDto(this.usuarioSessionDto);
            this.clienteView.setResizable(true);
            this.clienteView.setClosable(true);
            this.clienteView.setVisible(true);
            frmPrincipal.jdstPrincipal.add(this.clienteView);
        } catch (Exception ex) {
            JLabel label = new JLabel("Error no controlado, intente nuevamente");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setRegistrarClientes

    /**
     *
     * @param evt
     */
    private void setRegistrarDatosFisioterapeuta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRegistrarDatosFisioterapeuta
        this.buscarClienteView = new frmBuscarCliente(this, this.operacion, "2");
        frmPrincipal.jdstPrincipal.add(this.buscarClienteView);
        this.buscarClienteView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.buscarClienteView.setUsuarioSessionDto(usuarioSessionDto);
        this.buscarClienteView.setResizable(true);
        this.buscarClienteView.setClosable(true);
        this.buscarClienteView.setVisible(true);
    }//GEN-LAST:event_setRegistrarDatosFisioterapeuta

    private void setMenuCierreCaja(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuCierreCaja
        // TODO add your handling code here:
        String ruta = "cieerre_de_caja.jrxml";
        Map params = new HashMap<>();
        Calendar today = new GregorianCalendar();
        Date currentDate = new Date();
        today.setTime(currentDate);

        String fecha_inicio = String.valueOf(today.get(Calendar.YEAR)) + "-" + String.valueOf(today.get(Calendar.MONTH) + 1) + "-" + String.valueOf(today.get(Calendar.DAY_OF_MONTH)) + " " + "00:00:00";
        String fecha_fin = String.valueOf(today.get(Calendar.YEAR)) + "-" + String.valueOf(today.get(Calendar.MONTH) + 1) + "-" + String.valueOf(today.get(Calendar.DAY_OF_MONTH)) + " " + "23:59:59";

        params.put("FECHA_INICIO", fecha_inicio);
        params.put("FECHA_FIN", fecha_fin);

        Util.generarReportes(ruta, params);
    }//GEN-LAST:event_setMenuCierreCaja

    /**
     *
     */
    private void setMenuClientesActivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuClientesActivos
        // TODO add your handling code here:
        String ruta = "clientes_activos.jrxml";
        Map params = new HashMap<>();
        Util.generarReportes(ruta, params);

    }//GEN-LAST:event_setMenuClientesActivos

    /**
     *
     * @param evt
     */
    private void setMenuCumpleanos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuCumpleanos
        // TODO add your handling code here:
        this.cumpleanosView = new frmReporteCumpleanos(this);
        frmPrincipal.jdstPrincipal.add(this.cumpleanosView);
        this.cumpleanosView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.cumpleanosView.setUsuarioSessionDto(usuarioSessionDto);
        this.cumpleanosView.setResizable(true);
        this.cumpleanosView.setClosable(true);
        this.cumpleanosView.setVisible(true);
    }//GEN-LAST:event_setMenuCumpleanos

    private void setRegistrarClienteIngresos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setRegistrarClienteIngresos
        this.clientesIngresosView = new frmClientesIngresos(this, operacion);
        frmPrincipal.jdstPrincipal.add(this.clientesIngresosView);
        this.clientesIngresosView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.clientesIngresosView.setUsuarioSessionDto(usuarioSessionDto);
        this.clientesIngresosView.setResizable(true);
        this.clientesIngresosView.setClosable(true);
        this.clientesIngresosView.setVisible(true);
    }//GEN-LAST:event_setRegistrarClienteIngresos

    /**
     *
     * @param evt
     */
    private void menuReporte_fisioterapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporte_fisioterapiaActionPerformed
        // TODO add your handling code here:
        this.reporteFisioterapiaView = new frmReporteFisioterapia(this);
        frmPrincipal.jdstPrincipal.add(this.reporteFisioterapiaView);
        this.reporteFisioterapiaView.setSize(frmPrincipal.jdstPrincipal.getWidth(), frmPrincipal.jdstPrincipal.getHeight() - 1);
        this.reporteFisioterapiaView.setUsuarioSessionDto(usuarioSessionDto);
        this.reporteFisioterapiaView.setResizable(true);
        this.reporteFisioterapiaView.setClosable(true);
        this.reporteFisioterapiaView.setVisible(true);
    }//GEN-LAST:event_menuReporte_fisioterapiaActionPerformed

    private void setMenuCrearUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuCrearUsuario
        try {
            this.usuarioView = new frmUsuarios(this, this.operacion);
            this.usuarioView.setTitle("Formulario para el registro de usuarios");
            this.usuarioView.setSize(this.getWidth(), this.getHeight() - 1);
            this.usuarioView.setUsuarioSessionDto(this.usuarioSessionDto);
            this.usuarioView.setResizable(true);
            this.usuarioView.setClosable(true);
            this.usuarioView.setVisible(true);
            frmPrincipal.jdstPrincipal.add(this.usuarioView);
        } catch (Exception ex) {
            JLabel label = new JLabel("Error no controlado, intente nuevamente");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setMenuCrearUsuario

    private void setMenuBuscarUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuBuscarUsuario
        
    }//GEN-LAST:event_setMenuBuscarUsuario

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frmPrincipal principal = new frmPrincipal();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        });
    }

    public frmClientesIngresos getClientesIngresosView() {
        return clientesIngresosView;
    }

    public void setClientesIngresosView(frmClientesIngresos clientesIngresosView) {
        this.clientesIngresosView = clientesIngresosView;
    }

    public frmRegistrarPagos getRegistrarPagosView() {
        return registrarPagosView;
    }

    public void setRegistrarPagosView(frmRegistrarPagos registrarPagosView) {
        this.registrarPagosView = registrarPagosView;
    }

    public frmBuscarCliente getBuscarClienteView() {
        return buscarClienteView;
    }

    public void setBuscarClienteView(frmBuscarCliente buscarClienteView) {
        this.buscarClienteView = buscarClienteView;
    }

    public frmReporteCumpleanos getCumpleanosView() {
        return cumpleanosView;
    }

    public void setCumpleanosView(frmReporteCumpleanos cumpleanosView) {
        this.cumpleanosView = cumpleanosView;
    }

    public frmFisioterapia getFisitorepiaView() {
        return fisitorepiaView;
    }

    public void setFisitorepiaView(frmFisioterapia fisitorepiaView) {
        this.fisitorepiaView = fisitorepiaView;
    }

    public frmDescuentos getDescuentoView() {
        return descuentoView;
    }

    public void setDescuentoView(frmDescuentos descuentoView) {
        this.descuentoView = descuentoView;
    }

    public frmCafeteria getCafeteriaView() {
        return cafeteriaView;
    }

    public void setCafeteriaView(frmCafeteria cafeteriaView) {
        this.cafeteriaView = cafeteriaView;
    }

    public frmProductos getProductoView() {
        return productoView;
    }

    public void setProductoView(frmProductos productoView) {
        this.productoView = productoView;
    }

    public frmPaquetes getPaqueteView() {
        return paqueteView;
    }

    public void setPaqueteView(frmPaquetes paqueteView) {
        this.paqueteView = paqueteView;
    }

    public frmClientes getClienteView() {
        return clienteView;
    }

    public void setClienteView(frmClientes clienteView) {
        this.clienteView = clienteView;
    }

    public frmPagos getPagosView() {
        return pagosView;
    }

    public void setPagosView(frmPagos pagosView) {
        this.pagosView = pagosView;
    }

    public UsuarioDto getUsuarioSessionDto() {
        return usuarioSessionDto;
    }

    public void setUsuarioSessionDto(UsuarioDto usuarioSessionDto) {
        this.usuarioSessionDto = usuarioSessionDto;
    }

    public Operaciones getOperacion() {
        return operacion;
    }

    public void setOperacion(Operaciones operacion) {
        this.operacion = operacion;
    }

    public frmUsuarios getUsuarioView() {
        return usuarioView;
    }

    public void setUsuarioView(frmUsuarios usuarioView) {
        this.usuarioView = usuarioView;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JDesktopPane jdstPrincipal;
    private javax.swing.JMenuItem menuBuscar_cliente;
    private javax.swing.JMenuItem menuBuscar_cliente1;
    private javax.swing.JMenuItem menuCafeteria;
    private javax.swing.JMenuItem menuCierre_caja;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuClientes_activos;
    private javax.swing.JMenuItem menuCrear_cliente;
    private javax.swing.JMenuItem menuCrear_usuario;
    private javax.swing.JMenu menuCumpleanos;
    private javax.swing.JMenuItem menuDescuentos;
    private javax.swing.JMenuItem menuPagos;
    private javax.swing.JMenuItem menuPaquetes;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuReporte_fisioterapia;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
